# CMakeList.txt : CMake project for Minimum_Spanning_Tree, include source and define
# project specific logic here.
#
include_directories (include)
# Add source to this project's executable.
add_executable (minimum_spanning_tree src/main.cpp src/Minimum_Spanning_Tree.cpp src/File.cpp src/Function_str.cpp)



# TODO: Add tests and install targets if needed.
